apiVersion: v1
kind: PersistentVolume
metadata:
  name: gitlab-postgresql
spec:
  capacity:
    storage: 400Mi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Delete
  storageClassName: my-storage-class
  volumeMode: Filesystem
  nfs:
    path: /var/lib/libvirt/images/ocp4-pv-user-pvs/gitlab4
    server: 192.168.50.1
