kind: Service
apiVersion: v1
metadata:
  name: gitlab
  namespace: gitlab
  labels:
    app: gitlab
    rht-gitops.com/openshift-gitops: gitlab
spec:
  ports:
    - name: ssh
      protocol: TCP
      port: 22
      targetPort: 22
    - name: http
      protocol: TCP
      port: 80
      targetPort: 80
  internalTrafficPolicy: Cluster
  sessionAffinity: None
  selector:
    app: gitlab