kind: Secret
apiVersion: v1
metadata:
  name: gitlab-secret
  namespace: gitlab
  labels:
    app: gitlab
    rht-gitops.com/openshift-gitops: gitlab
data:
  DB_PASS: XXXXXXXX
  GITLAB_ROOT_PASSWORD: XXXXXXXX
  GITLAB_SECRETS_DB_KEY_BASE: XXXXXXXX
  GITLAB_SECRETS_OTP_KEY_BASE: XXXXXXXX
  GITLAB_SECRETS_SECRET_KEY_BASE: XXXXXXXX
  SMTP_PASS: XXXXXXXX
type: Opaque
