apiVersion: v1
kind: PersistentVolume
metadata:
  name: gitlab-main
spec:
  capacity:
    storage: 400Mi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Delete
  storageClassName: my-storage-class
  volumeMode: Filesystem
  nfs:
    path: /var/lib/libvirt/images/ocp4-pv-user-pvs/gitlab1
    server: 192.168.50.1   
