kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: gitlab-persistent-storage
  namespace: gitlab
  labels:
    app.kubernetes.io/component: master
    app.kubernetes.io/instance: gitlab
    app.kubernetes.io/name: redis  
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 400Mi
  storageClassName: my-storage-class
  volumeMode: Filesystem 
