apiVersion: v1
kind: Secret
metadata:
  name: gitlab-runner-secret
# Only one of the following fields must be set. The Operator will fail to register Runner if both are provided.
# # NOTE: runner-registration-token is deprecated and will be removed in GitLab 18.0. You should use runner-token instead.
type: Opaque  
stringData:
  runner-token: XXXXXX # your project runner token

# runner-registration-token: "" # your project runner secret
